cluster.name: "docker-cluster"
network.host: 0.0.0.0

xpack.security.enabled: true

xpack.security.transport.ssl:
    enabled: true
    verification_mode: certificate
    keystore.path: "/usr/share/elasticsearch/config/certs/elastic-certificates.p12"
    truststore.path: "/usr/share/elasticsearch/config/certs/elastic-certificates.p12"
# xpack.security.transport.ssl.enabled: true
# xpack.license.self_generated.type: trial